### ISSUE TITLE
Change NODE_ENV check to be against 'production'

### ISSUE THREAD

**Issue by damonmaria** [xolvio/cleaner#12]
I'd trying to use a separate `NODE_ENV` for testing: `NODE_ENV=test meteor ...`

But xolvio:cleaner currently checks `process.env.NODE_ENV !== 'development'`and blows up.

I think it would be better and more flexible to change this check to: `process.env.NODE_ENV === 'production'`, as this will allow other environments. 

Does this sound like a good idea?

**Comment by ghost** [comment]
I'd recommend to use another environment variable to determine if you are in testing mode. E.g. 'IS_TESTING=true'. The Meteor CLI will always set NODE_ENV to development in development mode.

**Comment by damonmaria** [comment]
Using the Meteor CLI, if I set `NODE_ENV=test` then I get the following from xolvio:cleaner:

```
resetDatabase is not allowed outside of a development mode. Aborting.
```

So my setting of `NODE_ENV` must be applying. I know in the past `meteor run` used to always override `NODE_ENV` to `development` but that doesn't appear to be the case anymore. I think [this PR](https://github.com/meteor/meteor/pull/6461) is the one that may have solved it. 

Using `NODE_ENV` also means other tools can switch on it. For example I use an `env` section in my `.babelrc` where I only want React hotloading in development (and not in test or production). `NODE_ENV` achieves this. Yes, I could use `BABEL_ENV` for this but `NODE_ENV` is designed for this purpose and is more generally applicable.
