### ISSUE TITLE
Feature Request: Whitelist Collections

### ISSUE THREAD

**Issue by workflow** [xolvio/cleaner#2]
# Example Use Case

I'm populating `meteor_accounts_loginServiceConfiguration` on `Meteor.startup()` only, would be nice to be able to keep that one collection's content accross scenarios.

**Comment by workflow** [comment]
Now that was fast :)

**Comment by ghost** [comment]
Yeah, I will need to write tests for the package before I release it though. You
can clone it for now.

Florian Peter notifications@github.com schrieb am So., 23. Aug. 2015
01:06:
