### ISSUE TITLE
Can't use on the client side?

### ISSUE THREAD

**Issue by sungwoncho** [xolvio/cleaner#4]
I haven't tested this, but the code seems like it won't work on the client side because of [this line](https://github.com/xolvio/cleaner/blob/master/cleaner.js#L27). Meteor won't let an untrusted code use an arbitrary Mongo selector with `collection.remove`.

This might be a problem when doing client integration tests.

If that's the case, how about implementing something like this PR by @riebeekn?
https://github.com/sungwoncho/factory-boy/pull/3

**Comment by ghost** [comment]
The function is only intended to run on the server. You would define a Meteor method that calls the resetDatabase function. Then you can call the Meteor method from the client side.

We could define a Meteor method for this in this package.

**Comment by sungwoncho** [comment]
I haven't read the README thoroughly enough:

> You can do this inside a Meteor method and call it from your client tests.

I think defining a method in the package sounds like a good idea. Will submit a PR.

**Comment by ghost** [comment]
Fixed by #10
