### ISSUE TITLE
Doesn't work with capped collections

### ISSUE THREAD

**Issue by cwohlman** [xolvio/cleaner#7]
Apparently you can't remove documents from a capped collection: https://docs.mongodb.org/manual/core/capped-collections/
I'm getting this error:

```
MongoError: cannot remove from a capped collection: meteor.useful:logs/logs
  @ Object.Future.wait (/Users/joshua/.meteor/packages/meteor-tool/.1.1.3.1rio88++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
  @ packages/meteor/helpers.js:119:1
  @ packages/xolvio_cleaner.js:41:5
```

The annoying thing is that this crashes my entire test, the only way to get my tests working is to temporarily convert my collection to an ordinary collection by commenting out the code that makes a capped collection.

If I get a chance I'll look into adding a pull request for this, it looks like it should be pretty simple to fix.

In the mean time fixing #6 would be a nice workaround.

**Comment by ghost** [comment]
I think 0.2.0 includes already the excludedCollections option. Let me know if not.

**Comment by cwohlman** [comment]
Cool, I'll check it out.
